# encoding: utf-8
## App and Company
app_name: "DeliveryAgents"
domain: "deliveryagents.de"
company_mail: "info@deliveryagents.de"

##################################################################################################################
##################################################################################################################
## A P I - K E Y S
##################################################################################################################
development:
  paypal_id:        ''
  paypal_secret:    ''
##################################################################################################################
test:
  paypal_id:        ''
  paypal_secret:    ''
##################################################################################################################
staging:
  paypal_id:        ''
  paypal_secret:    ''
##################################################################################################################
production:
  paypal_id:        ''
  paypal_secret:    ''
##################################################################################################################
google_analytics_key:       'UA-xxx-1'
google_webmaster_key:       'XX-xx-XX'